version: "3.9"

services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=plusme
      - POSTGRES_USER=plusme
      - POSTGRES_PASSWORD=plusme
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8100
    volumes:
      - .:/code
    ports:
      - "8100:8100"
    depends_on:
      - db
  redis:
    image: redis:6.2.6
  celery:
    restart: always
    build: .
    command: celery -A wepublic_backend worker --loglevel=debug # --logfile=logs/celery.log # Command used to start the Celery worker in the Docker container
    volumes:
      - .:/code
    depends_on:
      - db
      - redis
      - web
